/**
 * This type represents the various operations that can be performed in a PostgreSQL query plan.
 * It includes operations like scans, joins, aggregates, and more.
 * Each operation corresponds to a specific type of node in the query execution plan.
 * The operations are used to describe how the database engine processes a query,
 * including how it accesses data, performs joins, aggregates results, and more.
 */
export type Operation =
  | "Seq Scan"
  | "Index Scan"
  | "Index-Only Scan"
  | "Nested Loop"
  | "Hash Join"
  | "Merge Join"
  | "Aggregate"
  | "Append"
  | "Bitmap Heap Scan"
  | "Bitmap Index Scan"
  | "BitmapAnd"
  | "BitmapOr"
  | "Custom Scan"
  | "CTE Scan"
  | "Foreign Scan"
  | "Function Scan"
  | "Gather"
  | "Gather Merge"
  | "Group"
  | "GroupAggregate"
  | "Hash"
  | "HashAggregate"
  | "HashSetOp"
  | "Incremental Sort"
  | "Limit"
  | "LockRows"
  | "Materialize"
  | "Memoize"
  | "Merge Append"
  | "MixedAggregate"
  | "ModifyTable"
  | "Parallel Bitmap Heap Scan"
  | "Parallel Index Scan"
  | "Parallel Index-Only Scan"
  | "Parallel Seq Scan"
  | "ProjectSet"
  | "Recursive Union"
  | "Result"
  | "SetOp"
  | "Sort"
  | "Subquery Scan"
  | "TID Scan"
  | "TID Range Scan"
  | "Unique"
  | "Values Scan"
  | "WindowAgg"
  | "WorkTable Scan";
